### ISSUE TITLE
Hi please help Exception error

### ISSUE THREAD

**Issue by markyder** [emoacht/SnowyImageCopy#12]
Hi I really want to use snowy to auto download pics from my camera but keep getting exception as per attached image, I have the flashcard set to station mode and am able to access via browser at http://flashair and see upload/ copy from no problems?

any help would be really appreciated, the machine is running win 7 with net 4.5.50709

thanks!

Mark
![snowy exception text](https://cloud.githubusercontent.com/assets/10786130/5988298/9b481106-a952-11e4-8bb2-20b4ba705c8e.jpg)
![snowy exception](https://cloud.githubusercontent.com/assets/10786130/5988299/a0ac8942-a952-11e4-8792-6d0228c27591.jpg)

**Comment by emoacht** [comment]
Hi, Mark,

Thanks for your report.
Let me look into it. Please wait for a while.

EMO

+++++
EMOTO Masayuki <emotomnf@nifty.com>

**Comment by emoacht** [comment]
Hi Mark,

Thank you for your report.
Let me look into it. Please wait for a while.

EMO

**Comment by emoacht** [comment]
Hi Mark,

I identified the code where the exception was thrown and it suggests that an unexpected file list data caused it. Something is wrong and I need to check the exact file list data. So, could you use /recordlog command line option and post the content of log file?

EMO

**Comment by markyder** [comment]
Ok thanks no prob where does that log go?

Regards

Mark Deragon
RedDoor Homes



On 1 Feb 2015, at 17:28, emoacht <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Mark,

I identified the code where the exception was thrown and it suggests that an unexpected file list data caused it. Something is wrong and I need to check the exact file list data. So, could you use /recordlog command line option and post the content of log file?

EMO

-

**Comment by markyder** [comment]
?hi thanks for your help, below is th content of download.log


[cid:732f13ff-7842-4ac1-bb1c-f5f51fac6074]

________________________________

**Comment by markyder** [comment]
I've uploaded the file and exception just in case thanks !!
![downloadlog](https://cloud.githubusercontent.com/assets/10786130/5993265/758b55b8-aa42-11e4-8309-1f001fa9f122.jpg)
![excepnew](https://cloud.githubusercontent.com/assets/10786130/5993272/92bdecae-aa42-11e4-9b50-c4ffa1d78127.jpg)

**Comment by emoacht** [comment]
Thanks Mark,

I found the time stamp of "DCIM" folder is 2014-13-28. It is quite unusual and the cause of the exception. I can suppress the exception and am going to do so but wonder some strange things happening in your camera or FlashAir. So one more thing, could you check the update time or created time of "DCIM" folder from the Explorer?

EMO

**Comment by markyder** [comment]
Hi strangely didn't have a date so deleted the folder and created another and all working !!1

Thank you so much!!

**Comment by markyder** [comment]
Hi, the directory DCIM didn't have a date for creation so I deleted and recreated and all worked, Thanks
 is there a way to rename the card so you can use more than one on a network ? and one  other thing is there a way to download other file types ? ie docs etc?

Thanks again for your help !

**Comment by emoacht** [comment]
Okay, anyway I will add some check algorithm to handle such a strange case.
Regarding FlashAir address, you can change address of each FlashAir card by editing CONFIG file in SD_WLAN folder. See [APPNAME](https://flashair-developers.com/en/documents/api/config/#APPNAME). Don't forget to set FlashAir address of Snowy to meet the address.
Regarding file types other than image files, I have no plan to add them at this moment because there will be so many things to think about to handle such files.

**Comment by emoacht** [comment]
In ver 0.9.9, I added algorithm to handle such invalid date or time. If the item is a folder, it will not hinder the operation. If the item is a file, the file will be copied to a folder named "Unknown" in the specified local folder.

**Comment by markyder** [comment]
Hi, am interested in doing some work with these wifi cards however would need some more functionality from the software for example software needs to see / copy all files

Is there a way to add multiple ssid's for the card to connect to.

I Would like to brand the software a bit

I Would like to add an auto format of the sd card option

Would like to call the devices web service something I could access over the Internet. And different for each one, maybe using no-ip as a DNS service.

Is this something you would be interested in performing for me, if so would you have a price in mind ? If all the functions could not be added which ones could?



Regards

Mark



On 12 Feb 2015, at 04:58, emoacht <notifications@github.com<mailto:notifications@github.com>> wrote:


In ver 0.9.9, I added algorithm to handle such invalid date or time. If the item is a folder, it will not hinder the operation. If the item is a file, the file will be copied to a folder named "Unknown" in the specified local folder.

-

**Comment by markyder** [comment]
Hi did you receive my email as per below?

Hi, am interested in doing some work with these wifi cards however would need some more functionality from the software for example software needs to see / copy all files

Is there a way to add multiple ssid's for the card to connect to.

I Would like to brand the software a bit

I Would like to add an auto format of the sd card option

Would like to call the devices web service something I could access over the Internet. And different for each one, maybe using no-ip as a DNS service.

Is this something you would be interested in performing for me, if so would you have a price in mind ? If all the functions could not be added which ones could?



Regards

Mark



On 12 Feb 2015, at 04:58, emoacht <notifications@github.com<mailto:notifications@github.com>> wrote:


In ver 0.9.9, I added algorithm to handle such invalid date or time. If the item is a folder, it will not hinder the operation. If the item is a file, the file will be copied to a folder named "Unknown" in the specified local folder.

**Comment by markyder** [comment]
Hi I just wondered if you received my email re possible doing some work (obviously on a paid basis) on your snowytool software

Regards

Mark Deragon
Director
RedDoor Homesn



On 2 Feb 2015, at 03:32, emoacht <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks Mark,

I found the time stamp of "DCIM" folder is 2014-13-28. It is quite unusual and the cause of the exception. I can suppress the exception and am going to do so but wonder some strange things happening in your camera or FlashAir. So one more thing, could you check the update time or created time of "DCIM" folder from the Explorer?

EMO

-
