### ISSUE TITLE
HttpRequestException: StatusCode: ServiceUnavailable

### ISSUE THREAD

**Issue by luogonglin** [emoacht/SnowyImageCopy#28]
THank you for your great application! Yesterday I met a tiny issue. Snowy issued an error says "SnowyImageCopy.Models.Exceptions.UnexpectedException:“Failed to check & copy files."",and inner exeception is "HttpRequestException: StatusCode: ServiceUnavailable" when the camera was turned off, so I added "case HttpStatusCode.ServiceUnavailable:" below line 588 in the FileManager.cs file, then this exeception was handled normally.

**Comment by emoacht** [comment]
Thanks luogonglin,
I check it and your fix seems good.  Are you sending a pull request or do you want me to do it?
