### ISSUE TITLE
FlashAir Question

### ISSUE THREAD

**Issue by coldmn3** [emoacht/SnowyImageCopy#29]
Hi emoacht, I'm doing some programming for FlashAir too. 
I have a question I wish you can help.
Is it possible downloading file and request api such as get file list (op=100) at the same time ?
I find out while i'm downloading some file, FlashAir will not respond api request any more(time out).

**Comment by emoacht** [comment]
Hi, coldmn,
I haven't tried multiple access at a time.
It seems that you got the [answer](https://flashair-developers.com/en/support/forum/#/discussion/2513/downloading-meanwhile-request-api) in FlashAir official forum.
