### ISSUE TITLE
Question about sorting the images

### ISSUE THREAD

**Issue by siburny** [emoacht/SnowyImageCopy#31]
Is there a way to do a reverse sort of the images? I would like the latest images to appear at the top.
Also, is it possible to just check for new images in the "Auto" (don't download them automatically)?

P.S. Thanks for the great software

**Comment by emoacht** [comment]
Hi, siburary,
> Is there a way to do a reverse sort of the images?
Currently no. But it sounds nice in some scenarios. I am working on it.
> Also, is it possible to just check for new images in the "Auto" (don't download them automatically)?
No. And I cannot imagine that auto without downloading images would be useful for most people. Usually, only checking images will not take a long time and there would be no substantial time saving by auto without downloading.

**Comment by siburny** [comment]
> Currently no. But it sounds nice in some scenarios. I am working on it.
Thanks!

**Comment by emoacht** [comment]
Release Ver 1.4.0.
You can reverse the order of images by setting "Order from newer images" in "File".
