### ISSUE TITLE
 Bug(?) report for option "Not select once-copied images on check"

### ISSUE THREAD

**Issue by dentphoto** [emoacht/SnowyImageCopy#49]
Snowy Plus 2.2.0 option "Not select once-copied images on check"
It doesn't work exactly.
However in the previous version  Snowy 1.9.0, it worked very accurately.

For verification, I did the following experiments.
1. Take 6 photos and wireless transferred.
2. Delete the photos sent to the local folder.
3. Close the Snowy app and Restart it.
4. Snowy 1.9.0 displays "once copied" and works correctly.
    But, Snowy PLUS randomly sends several files AGAIN. (Maybe a bug??)

# Snowy 1.9 test1 : http://www.youtube.com/watch?v=bc-TyWxf2rc
# Snowy 1.9 test2 : http://www.youtube.com/watch?v=XhKYhomT2bM
# Snowy Plus test1 : http://www.youtube.com/watch?v=2ECNlG9kycE
# Snowy Plus test2 : http://www.youtube.com/watch?v=w4qtwkN_3gA

**Comment by dentphoto** [comment]
Even with Snowy Plus, it works normally if only one window is opened.
It seems to malfunction only when two or more windows are open.

**Comment by emoacht** [comment]
@dentphoto Thank you for reporting.
It is a big. Working on.

**Comment by emoacht** [comment]
I hope it is fixed by https://github.com/emoacht/SnowyImageCopy/commit/b6ae9ffcddd9e769bab24bc9bd6a6341c9584b42
I pushed this updated version into the pipeline.

**Comment by dentphoto** [comment]
Thank you so much.
However, it has not been updated yet in Microsoft Store.

**Comment by emoacht** [comment]
It seems to be published in the Store. 3 days. It took 3 days. so-so.

**Comment by dentphoto** [comment]
It seems to work perfectly~^.^
Thank you.

# Snowy 2.2.1 => http://www.youtube.com/watch?v=3ebicntM14Q&t=15s

**Comment by emoacht** [comment]
@dentphoto Thank you for confirming it.
