### ISSUE TITLE
Add exit buttons in switch box

### ISSUE THREAD

**Issue by dentphoto** [emoacht/SnowyImageCopy#51]
Hi~~Emoacht
What do you think about adding a few buttons to the switch box?
Present vs Wish
![Switch](https://user-images.githubusercontent.com/60927347/92611352-a8baa380-f2f3-11ea-819a-f76aa99692c4.png)
![switch-modify](https://user-images.githubusercontent.com/60927347/92611373-ae17ee00-f2f3-11ea-8491-222a611003e4.png)

**Comment by emoacht** [comment]
@dentphoto I had thought about the same thing when designing this menu but rejected it because closing a window should be done by the window's close button to prompt a user to make sure which window the user is about to close and whether the window is ready to be closed.

**Comment by dentphoto** [comment]
Oh~You have considered it in advance.
Yes. Okay.
