### ISSUE TITLE
Automatic timeout settings of local card

### ISSUE THREAD

**Issue by dentphoto** [emoacht/SnowyImageCopy#52]
What does "Automatic timeout ON/OFF" mean in AP mode setting?
And the unit is seconds? minute?

![AP mode timeout](https://user-images.githubusercontent.com/60927347/92991988-53b0a480-f522-11ea-8958-163177f9729c.jpg)

**Comment by emoacht** [comment]
It's automatic timeout length in seconds.
Please refer to the help of [FlashAirTool](https://jp.toshiba-memory.com/ww/support/download/flashair/w04/config02.htm) by KIOXIA 

> （Auto Start Timeout Setting）
If there is no attempt to connect to the FlashAir™ card from a device (e.g. smartphone) within the time set in the timeout setting, the wireless LAN functionality automatically turns off.
To restart the wireless LAN functionality, turn off the device that the FlashAir™ is inserted into and then turn it on again.

**Comment by dentphoto** [comment]
Thanks for kind answer.
