### ISSUE TITLE
Order and description of settings in Options

### ISSUE THREAD

**Issue by dentphoto** [emoacht/SnowyImageCopy#81]
[Suggestion 1]
The Standard version includes the first 7 basic options out of total 11 of Plus version.
I think it's appropriate to swap the positions of the following two options:
Because [Do not overwrite existing file] is an advanced user option that is sometimes necessary 
but infrequently preferred, it is proper to be included in the Plus version.
On the other hand, [Do not select once copied file on check] is the universal option to check most of the time,
so I think it's appropriate to include it in the Standard version.
What do you think about repositioning these two options? 

[Suggestion 2]
In [Do not overwrite existing file], "existing file" does not mean exactly the same file. 
However, some people misunderstand that it means the same file. 
How about replacing it with a detailed description? 
For example, 
[Do not overwrite existing file of same filename but different exif] 

![option swap](https://user-images.githubusercontent.com/60927347/153705243-1ea3f983-2a8d-4b52-8daa-c92829925567.jpg)

**Comment by emoacht** [comment]
Thanks for the suggestions.
Suggestion 1: I don't think so.
Suggestion 2: I understand your point but it should be solved in other way.

**Comment by emoacht** [comment]
Regarding suggestion 2, I guess that the value of date taken in Exif matches the time when a camera saves the image into FlashAir card. Of course, it depends on the camera model but checking my Canon's, they seem to match.
So, assuming that's the case, we can make use of the time to determine if the image is identical even if some changes, including the orientation, are added to the file.

**Comment by dentphoto** [comment]
Without mentioning the exif, 
Can we simply think of [Do not overwrite existing file of same filename but different file size]?

**Comment by emoacht** [comment]
It looks confusing and will raise question about the case of the same file name and same file size.

**Comment by emoacht** [comment]
I added explanation to readme. I hope a user to refer it when the user has any question on this.
